services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports: 
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    networks:
      - bridge_net

  exp_tracker:
    image: exp-tracker:dev
    container_name: exp-tracker
    restart: always
    command: uv run main
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      TELEGRAM_BOT_TOKEN: vwrvt4b
    networks:
      - bridge_net
  
  blob_storage:
    image: mcr.microsoft.com/azure-blob-storage:latest
    container_name: exp_tracker_blob
    environment:
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
    restart: always
    ports:
    - "11002:11002"
    volumes:
    - blob_data:/workdir

volumes:
  blob_data:

networks:
  bridge_net:
    external: true
    name: bridge