services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports: 
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    networks:
      - bridge_net

  exp_tracker:
    image: exp-tracker:dev
    container_name: exp-tracker
    restart: always
    command: uv run main
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      TELEGRAM_BOT_TOKEN: vwrvt4b
    networks:
      - bridge_net

networks:
  bridge_net:
    external: true
    name: bridge