[project]
name = "adk-exp-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beanie>=2.0.1",
    "google-adk>=1.21.0",
    "pymongo>=4.15.5",
    "python-telegram-bot>=22.5",
]
